### ISSUE TITLE
Board jumper removal reminder should be shown on board detection page prior to flashing

### ISSUE THREAD

**Issue by mitant** [Rat-OS/RatOS-configurator#13]
With the Octopus 1.1 Pro H723 the boot jumper removal reminder does not show after flashing so it looks like the flash failed or the board is unresponsive.  

Instead, show any board reminders on the board detection page so the user has a chance to realize they need to remove the jumper after flashing to proceed to step 2 and onwards.

PR coming soon

**Comment by miklschmidt** [comment]
Fixed in `development` (2.1)
