### ISSUE TITLE
ADXL345 pin incorrectly configured for BTT SKR Pro 1.2

### ISSUE THREAD

**Issue by david-antos** [Rat-OS/RatOS-configurator#52]
### What happened

RatOS.cfg for BTT SKR Pro 1.2 (at least on my V-Core 3) gets

```
[adxl345 controlboard]
cs_pin: PB12
```

and according to the documentation (unchanged at least since RatOS 2.0 and probably longer), CS should be connected to PA15.

Board aliases are OK, I believe the pin name is taken from configuration/boards/btt-skr-pro-12/board-definition.json

### What did you expect to happen

The config should be generated with cs_pin: PA15.

### How to reproduce

Install RatOS 2.1.x and configure BTT SKR Pro 1.2.

**Comment by miklschmidt** [comment]
Good catch, not sure how that got messed up, fixed in `development`!
